spring:
  application:
    name: com.application.food.delivery
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: service.cab.app@gmail.com
    password:   # your Gmail App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
fast2:
  sms:
    api-key: 
    url: https://www.fast2sms.com/dev/bulkV2
    content-type: application/json


  jpa:
    hibernate:
      ddl-auto: update   # options: create | update | validate | none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
kafka:
  bootstrap-servers: localhost:9092   # your local Kafka broker
  consumer:
    group-id: food-delivery-group     # unique group id for consumers
    auto-offset-reset: earliest       # consume from beginning if no offset found
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8090

logging:
  level:
    org.apache.kafka: ERROR
    org.apache.kafka.clients.NetworkClient: ERROR